# KEEP THE MARGINS AND FILE STRUCTURE!!!
# Proxmox node address and authorization information
proxmox:
  url:
    ip: 127.0.0.1
    port: 8006
  auth:
    username: 'root@pam'
    password: 'PASSWORD'

# Balancing Parameters
parameters:
  mem_deviation: 4 # Percentage of allowable deviation of the RAM load of the node
  threshold: 90            # Percentage of maximum load
  cpu_deviation: 1 # Percentage of allowable deviation of the CPU load of the node
  cpu_deviation_duration_seconds: 20 # Time of allowable duration of the CPU exceed deviation
  lxc_migration: OFF       # Container migration (LXCs are rebooted during migration!!!)
  migration_timeout: 1000  # For the future
  only_on_master: OFF      # Only run PLB on the current cluster master

# List of exclusions
exclusions:
  vms: []    # Example: [100] or [100, 101, 102, 113, 125, 131] or ["100-200", 300, 301]
  nodes: []  # Example: [px-3] or [px-3, px-4, px-8, px-9]

# Loguru settings
logging_level: 'INFO'  # You can choose 'DEBUG" or "INFO" or "WARNING" or "ERROR"

# Mail settings
mail:
  sending: OFF # ON or OFF (Enables/disables sending email)
  message_subject: 'Load-balancer notification'
  from: 'user@domain.com'
  to: 'admin@domain.com'
  login: 'user' # Login options: login, domain\login, login@domain.com
  password: 'MAIL_PASSWORD'
  server:
    address: 'mx.domain.com' # IP or address of your mail server
    port: 25
  ssl_tls: OFF # ON or OFF

# Others
Gigabyte: 1073741824 # 1e+9 for 10^9
Terabyte: 1099511627776 # 1e+12 for 10^12

